### ISSUE TITLE
Website not accessible

### ISSUE THREAD

**Issue by shiryz** [FACN7/HIO-team#16]
You only get 65% in an audit

**Comment by HosenAgbaria** [comment]
hi how did you got this score ? i now checked and i got this ..
![acsess](https://user-images.githubusercontent.com/50136716/64765581-0e434b00-d54d-11e9-8995-0e1fb92d0f51.JPG)

**Comment by shiryz** [comment]
I ran an audit in the inspector, this is the result
![Screenshot from 2019-09-12 11-40-12](https://user-images.githubusercontent.com/22002193/64768510-40a37700-d552-11e9-8ca2-37901e7c8565.png)
