### ISSUE TITLE
Style comments

### ISSUE THREAD

**Issue by shiryz** [FACN7/HIO-team#23]
- Nav bar 
  - Text is too small on desktop, it is pretty unnoticeable for a user
  - Why is there a github logo that links back to your website in the middle?
  - Smaller font on mobile where it should be quite obvious
- Alignment: Please make sure your alignment is pixel perfect so it looks professional
- Colors are a bit plain, use more lively colors to attract the user
- White space, while having white space is really good, too much of it makes it look empty. Your mobile design has too much empty space

**Comment by ebraheemabbas** [comment]
fixed
